apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::145097883518:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MZKMCS7GXEUZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::145097883518:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-22T08:28:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1660"
  uid: 544cc9d9-30c6-45a1-b3d5-5dbace7c3bc8
